spawn_robot:
  ros__parameters:
    robot_name: "" # name of the robot, certain topic names are namespaced with this name
    sdf_file: "jetbot/model.sdf" # path to the sdf file in the share folder of the package
    world: "maze" # name of the world in which the robot should be spawned
    use_imu: true
    # start pose of the robot (atlas) in the world -7.0 0.0 3.96 0.0 0.0 0.0
    x: "-3.0"
    y: "-3.0"
    z: "0.2"
    roll: "0.0"
    pitch: "0.0"
    yaw: "0.0"
